.PHONY: install
install:
	@cp ../qpack.h $(INSTALL_PATH)/include/qpack.h
	@cp $(FN) $(INSTALL_PATH)/lib/$(FN)

.PHONY: uninstall
uninstall:
	@rm -f $(INSTALL_PATH)/include/qpack.h
	@rm -f $(INSTALL_PATH)/lib/$(FN)
