.PHONY: install
install:
	@cp ../qpack.h /usr/include/qpack.h
	@cp libqpack.so /usr/lib/x86_64-linux-gnu/libqpack.so

.PHONY: uninstall
uninstall:
	@rm -f /usr/include/qpack.h
	@rm -f /usr/lib/x86_64-linux-gnu/libqpack.so
